version: '3'
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:80
    volumes:
      - .:/var/www
    networks:
      - lerd
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'lerd'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - lerdmysql:/var/lib/mysql
    networks:
      - lerd

  redis:
    image: redis:alpine
    volumes:
      - lerdredis:/data
    networks:
      - lerd

networks:
  lerd:
    driver: bridge

volumes:
  lerdmysql:
    driver: local
  lerdredis:
    driver: local
